### health
GET http://localhost:8080/

### extrato do cliente
GET http://localhost:8080/clientes/1/extrato
Content-Type: application/json

### transacao
POST http://localhost:8080/clientes/2/transacoes
Content-Type: application/json

{
  "valor": 1000,
  "tipo" : "c",
  "descricao" : "descricao"
}
